In \[1\]:

    import numpy as np

In \[3\]:

    my_list=[10,20,30,40,50]
    arr=np.array(my_list)
    print(arr)

    [10 20 30 40 50]

### Properties of the array<a href="#Properties-of-the-array" class="anchor-link">¶</a>

In \[5\]:

    my=[10,20,30,40,50]
    arr=np.array(my)
    print(arr)
    print("size is:",arr.size)
    print("datatype is:",arr.dtype)
    print("dimension is:",arr.ndim)
    print("shape is:",arr.shape)

    [10 20 30 40 50]
    size is: 5
    datatype is: int64
    dimension is: 1
    shape is: (5,)

In \[11\]:

    my=[[10,23],[20,30],[40,50]]
    arr1=np.array(my)
    print(arr)
    print("size is:",arr1.size)
    print("datatype is:",arr1.dtype)
    print("dimension is:",arr1.ndim)
    print("shape is:",arr1.shape)

    [10 20 30 40 50]
    size is: 6
    datatype is: int64
    dimension is: 2
    shape is: (3, 2)

### ArrayList<a href="#ArrayList" class="anchor-link">¶</a>

In \[13\]:

    my_list=[10,20,30,40]
    arr=np.array(my_list)
    print("elements:")
    for i in range(0,len(my_list)):
        print(my_list[i])

    elements:
    10
    20
    30
    40

In \[15\]:

    my_list=[[10,20,70],[30,40,80],[50,60,90]]
    arr=np.array(my_list)
    print(arr)
    print("elements:")
    for i in arr:
        for j in i:
            print(j,end=' ')
        print()

    [[10 20]
     [30 40]
     [50 60]]
    elements:
    10 20 
    30 40 
    50 60 

### Submatrix from matrix slicing<a href="#Submatrix-from-matrix-slicing" class="anchor-link">¶</a>

In \[18\]:

    my_list=[[10,20,70],[30,40,80],[50,60,90]]
    arr=np.array(my_list)
    res1=arr[:,:]
    res2=arr[0:3,2:3]
    print(res1)
    print()
    print(res2)
    print()

    [[10 20 70]
     [30 40 80]
     [50 60 90]]

    [[70]
     [80]
     [90]]

### Creating one dimensional array:-\><a href="#Creating-one-dimensional-array:-%3E" class="anchor-link">¶</a>

In \[20\]:

    arr=np.ndarray(shape=5, dtype=int)
    print("enter the elements:")
    for i in range(0,arr.size):
        arr[i]=int(input())
    print("array elements are:",arr)

    enter the elements:

    array elements are: [12 13 14 15 11]

### Creating one dimensional array:-\><a href="#Creating-one-dimensional-array:-%3E" class="anchor-link">¶</a>

In \[21\]:

    n=int(input())
    arr=np.ndarray(shape=n,dtype=int)
    print("enter elements:")
    for i in range(n):
        arr[i]=int(input())
    print(arr)

    enter elements:

    [1 2 3 4 5]

In \[22\]:

    n=int(input())
    arr=np.ndarray(shape=n)
    print("enter elements:")
    for i in range(n):
        arr[i]=input()
    print(arr)

    enter elements:

    [1. 2. 3. 4. 5.]

In \[24\]:

    n=int(input())
    arr=np.ndarray(shape=n,dtype=str)
    print("enter elements:")
    for i in range(n):
        arr[i]=input()
    print(arr)

    enter elements:

    ['' '' '' '' '']

### Creating 2D array<a href="#Creating-2D-array" class="anchor-link">¶</a>

In \[25\]:

    r=int(input("enter rows:"))
    c=int(input("enter columns:"))
    arr=np.ndarray(shape=(r,c), dtype=int)
    print("size of the array is:",arr.size)
    print("shape of the array is:",arr.shape)
    print("dimension of the array is:",arr.ndim)
    print("datatype of the array is:",arr.dtype)

    size of the array is: 6
    shape of the array is: (3, 2)
    dimension of the array is: 2
    datatype of the array is: int64

### Reading elements into matrix:-\><a href="#Reading-elements-into-matrix:-%3E" class="anchor-link">¶</a>

In \[2\]:

    import numpy as np

In \[4\]:

    r=int(input("enter rows:"))
    c=int(input("enter columns:"))
    arr=np.ndarray(shape=(r,c),dtype=int)
    for i in range(r):
        for j in range(c):
            arr[i][j]=int(input())
    print("Array elements are:")
    print(arr)

    Array elements are:
    [[1 2 3]
     [4 5 6]
     [7 8 9]]

### Multi-Dimesional Arrays:-\><a href="#Multi-Dimesional-Arrays:-%3E" class="anchor-link">¶</a>

In \[ \]:

    r=int(input("enter rows:"))
    c=int(input("enter columns:"))
    z=int(input("enter value for x axis:"))
    arr=np.ndarray(shape=(r,c,z),dtype=int)
    for i in range(r):
        for j in range(c):
            for k in range(z):
                arr[i][j][k]=int(input())
    print("Array elements are:")
    print(arr)

### reshape()<a href="#reshape()" class="anchor-link">¶</a>

In \[6\]:

    list1=[10,20,30,40,50,60]
    arr=np.array(list1)
    print("dimension of the array is:",arr.ndim)
    arr2=arr.reshape(2,3)
    print(arr2)
    print("dimension of the new array is:",arr2.ndim)

    dimension of the array is: 1
    [[10 20 30]
     [40 50 60]]
    dimension of the new array is: 2

In \[ \]: